services:
  frontend:
    container_name: "frontend"
    build: frontend/
    ports:
      - "3000:3000"
    depends_on:
      - jenkins
    environment:
      JENKINS_URL: "http://jenkins:8080"

  jenkins:
    container_name: jenkins-platypus
    build: jenkins/
    image: jenkins:jcasc
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - jenkins-platypus-data:/var/jenkins_home
      - ./jenkins/tester/main.py:/var/jenkins_home/main.py:ro
      - ./jenkins/jenkins/casc.yml:/var/jenkins_home/casc_configs/casc.yaml:ro
      - ./jenkins/jenkins/job_dsl.groovy:/var/jenkins_home/job_dsl.groovy:ro
      - ./jenkins/binary:/opt/jenkins/binary:ro
      - ./jenkins/json:/opt/jenkins/json:ro
    environment:
      FRONTEND_URL: "http://localhost:3000/"
      CASC_JENKINS_CONFIG: "/var/jenkins_home/casc_configs"
      USER_ADMIN_PASSWORD: "admin"
      USER_API_PASSWORD: "api"
      BINARY: "/opt/jenkins/binary"
      JSON: "/opt/jenkins/json"
    entrypoint:
      - "/usr/bin/tini"
      - "--"
      - "/usr/local/bin/jenkins.sh"

volumes:
  jenkins-platypus-data: {}
