jenkins:
  systemMessage: "Welcome to the Platypus Checker"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "admin"
          password: "${USER_ADMIN_PASSWORD}"
        - id: "api"
          name: "api"
          password: "${USER_API_PASSWORD}"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - entries:
              - user: "admin"
            name: "Admin"
            pattern: ".*"
            description: "Me :)"
            permissions:
              - "Overall/Administer"
          - entries:
              - user: "api"
            name: "API"
            pattern: ".*"
            description: "For the api"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "View/Read"
          - entries:
            name: "Tek"
            pattern: ".*"
            description: "Regular Tek"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Workspace"
              - "Job/Read"
              - "Job/Move"

unclassified:
  accessControlsFilter:
    allowedHeaders: "Authorization, Content-Type"
    allowedMethods: "GET, POST, OPTIONS"
    allowedOrigins: "${FRONTEND_URL}"
    enabled: true

# WARN: To disbale script security un-comment those line
# security:
#   globalJobDslSecurityConfiguration:
#     useScriptSecurity: false

appearance:
  themeManager:
    disableUserThemes: false
    theme: "dark"
# NOTE: Available option : darkSystem, dark. There is not Light so just comment this to get light.

jobs:
  - file: /var/jenkins_home/job_dsl.groovy
